### ISSUE TITLE
[scitos_teleop] js parameter to launch file is ignored

### ISSUE THREAD

**Issue by hawesie** [strands-project/scitos_apps#26] opened 2013-08-21 12:54 UTC
If I launch the teleop node following [the instructions](https://github.com/strands-project/autonomous_patrolling/blob/master/README.md) it appears that the js parameter is ignored. E.g.

``` bash
strands@bob:~$ roslaunch scitos_teleop teleop_joystick.launch js:=/dev/input/rumblepad
... logging to /home/strands/.ros/log/dc6a234e-0a5d-11e3-9394-843a4b7f1c04/roslaunch-bob-16973.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://bob:45471/

SUMMARY
========

PARAMETERS
 * /joystick/autorepeat_rate
 * /joystick/dev
 * /rosdistro
 * /rosversion
 * /teleop_base/scale_angular
 * /teleop_base/scale_linear

NODES
  /
    joystick (joy/joy_node)
    teleop_base (scitos_teleop/teleop_base)
    teleop_head (scitos_teleop/head_teleop.py)
    teleop_joystick (scitos_teleop/rumble_control)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[joystick-1]: started with pid [16991]
[ERROR] [1377089477.529733702]: Couldn't open joystick /dev/js1. Will retry every second.
```

However, setting the associated environment variable does work

``` bash
strands@bob:~$ JOYSTICK_DEVICE=/dev/input/rumblepad roslaunch scitos_teleop teleop_joystick.launch 
... logging to /home/strands/.ros/log/dc6a234e-0a5d-11e3-9394-843a4b7f1c04/roslaunch-bob-17901.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://bob:50833/

SUMMARY
========

PARAMETERS
 * /joystick/autorepeat_rate
 * /joystick/dev
 * /rosdistro
 * /rosversion
 * /teleop_base/scale_angular
 * /teleop_base/scale_linear

NODES
  /
    joystick (joy/joy_node)
    teleop_base (scitos_teleop/teleop_base)
    teleop_head (scitos_teleop/head_teleop.py)
    teleop_joystick (scitos_teleop/rumble_control)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[joystick-1]: started with pid [17919]
process[teleop_joystick-2]: started with pid [17939]
process[teleop_base-3]: started with pid [17952]
process[teleop_head-4]: started with pid [17968]
```

Am I doing something wrong or is there a bug in the parameter handling?

**Comment by cdondrup** [comment] 2013-08-21 13:03
This is a bug. Will fix.

**Comment by cdondrup** [comment] 2013-08-21 13:24
Works as intended now.
Closing #26 via #27

**Closed as completed by cdondrup** 2013-08-21 13:24 UTC
Labels: bug
