### ISSUE TITLE
[scitos_docking] undock action returns aborted in simulation

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/scitos_apps#45] opened 2013-10-18 16:51 UTC
When I try to undock in simulation, the robot undocks, but the action finishes outcome aborted.

In the GUI I sometimes see the message: Message: afraid that it crashed,thoungh not everytime.

Didn't test this in the real robot, Bob is still on the sidelines recovering from injury

**Comment by gestom** [comment] 2013-10-19 02:31
Hi, is the error repeatable ? 
Can you send me the output of "rosrun scitos_docking visual_charging_client undock 100"

**Comment by bfalacerda** [comment] 2013-10-19 10:33
Yes, whenever I try to use the undocking action in simulation this happens. I'll send you the output Monday

**Comment by gestom** [comment] 2013-10-20 12:34
The most likely reason is the required precision of the final adjusting step of the visual charging.
This might not be achievable in simulation. I have decreased the precision in the latest pull request,  check it out.

**Comment by bfalacerda** [comment] 2013-10-21 08:58
It continues giving failure. Here is the final lines of output:

Charging preparing for autonomous run, Progress: 96%
Charging preparing for autonomous run, Progress: 96%
Charging preparing for autonomous run, Progress: 96%
Charging preparing for autonomous run, Progress: 97%
Charging preparing for autonomous run, Progress: 97%
Charging preparing for autonomous run, Progress: 97%
Charging preparing for autonomous run, Progress: 98%
Charging preparing for autonomous run, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging adjusting undock pose, Progress: 98%
Charging afraid that it crashed, Progress: 98%
Charging idle, Progress: 100%
Finished in state [ABORTED]
Answer: Undocking  not completed.
Charging client terminating.

**Comment by gestom** [comment] 2013-10-22 10:57
After the robot leaves the charging station, it attempts to adjust its pose relatively to the station.
The last parameter of the adjust method in docking.cpp file at line 235 corresponds to the required positioning precision.
With a real robot, I could set the precision up to 0.001m. However, the dynamic model of the robot in the simulator probably differs from the real one, so the controller for the real robot does not achieve the required precision in the simulation (this has been already encountered by @kunzel some time ago with charging)
To make the undocking work in simulation, you can try to set the precision lower, e.g. 0.05m.

**Comment by bfalacerda** [comment] 2013-10-22 11:10
Is this parameter in the parameter server? I think that for the patrolling we can be less strict about the undocking precision, and it would be cool if we can configure it in the launch file.

**Comment by gestom** [comment] 2013-10-22 11:12
Did you try it ? The reason might be different.

**Comment by bfalacerda** [comment] 2013-10-22 11:36
Just tried and it didn't work anyway, the problem is in the first adjust step. I also realized that I was not using the right version of the undocking in the tests, here's the output I get with the version in your repo:

Charging preparing for autonomous run, Progress: 96%
Charging preparing for autonomous run, Progress: 96%
Charging preparing for autonomous run, Progress: 97%
Charging preparing for autonomous run, Progress: 97%
Charging preparing for autonomous run, Progress: 97%
Charging preparing for autonomous run, Progress: 98%
Charging preparing for autonomous run, Progress: 98%
Charging preparing for autonomous run, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging adjusting undock pose - step 1, Progress: 98%
Charging afraid that it crashed, Progress: 98%
Charging idle, Progress: 100%
Finished in state [ABORTED]

**Comment by gestom** [comment] 2013-10-29 16:01
We had a look at it with @Jailander  and its caused by the fact that the PTU does not turn in simulation. Is the PTU actually working ?

**Comment by kunzel** [comment] 2013-10-29 18:06
@gestom , @Jailander, can you please update strands_morse and strands_utils to the latest versions? I've just renamed the topic name to '/ptu/cmd/' to reflect the topic name of the real robot. Then, it should work. (cf. also  https://github.com/strands-project/strands_morse/issues/55)

**Comment by Jailander** [comment] 2013-10-29 18:09
Great thank you, I will try it right now and let you know

**Comment by Jailander** [comment] 2013-10-30 09:58
Hi now with the PTU issue solved, I have tested undocking in simulation and it still fails but it is a completely different problem, @gestom and I will look into it today

**Comment by Jailander** [comment] 2013-10-30 17:15
Hi, the problem is now solved, it should work in simulation as it does in the robots, if it doesn't work on the first attempt try to recalibrate.

**Comment by bfalacerda** [comment] 2013-10-30 17:22
thank you, I will try it

**Comment by Jailander** [comment] 2014-01-25 16:14
I'm going to close this issue since it was solved a long time ago

**Closed as completed by Jailander** 2014-01-25 16:14 UTC
