### ISSUE TITLE
docking in the dark

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/scitos_apps#40] opened 2013-10-11 13:43 UTC
I'm pretty sure Bob failed to dock last night because it was dark and it couldn't see the robot station marker. For doing overnight runs we'll have to take care of this problem somehow

**Comment by nilsbore** [comment] 2013-10-11 14:28
![screenshot from 2013-10-11 16 21 59](https://f.cloud.github.com/assets/4670159/1315072/3ff07bc0-3281-11e3-978e-e57aaa25f467.png)
@gestom Can you make it work with the IR image instead?

**Comment by gestom** [comment] 2013-10-11 14:32
I have tried already. The problem is that it did not work well for longer distances.

**Comment by bfalacerda** [comment] 2013-10-12 16:31
I think that we can assume that the robot will always position itself in front of the charging station before starting the docking behaviour, thus if it works well for distances below 2 meters, that would be enough

**Comment by gestom** [comment] 2013-10-12 21:33
Hi, I have done some tests today and encountered the following problems:
1) IR and RGB cannot be streamed simultaneously. The openni driver decides if to stream RGB or IR based on the number of subscribers. If there is one or more subscriber to RGB, IR stream is switched off. 
2) The images we get from the /head_xtion/ir/image_raw look much worse than the image from Nils. @nilsbore Nils, did you obtain the aforeposted image from this ROS topic ?

To solve the docking in case of low visibility, we can go for following solutions:

1) Using SICK to identify the station: Feasible, laborious and probably not as reliable as the visual charging.
2) Using IR: Possible if the planner ensures that all subscribers for RGB are turned off prior to running the charging process.
3) Keep the charging station's room lights on. Definitely preferable for me. 
4) Attach ![lol](https://f.cloud.github.com/assets/4293593/1320913/d06ec026-3385-11e3-93c0-02c359a986e1.jpg) to the PTU base and use the 12V line (that is avail at the PTU base) to power it. The dynamic reconfiguration ability of scitos_mira can be used to switch the spotlight on and off. Simply awesome.

**Comment by hawesie** [comment] 2013-10-14 09:11
This raises tons of interesting issues. 

For 2) I think we can get the controller to turn off RGB subscribers.

3) is not possible for us. We don't have control of the the lights where our charging station is, as was evidenced by the failure that caused this. AFAIK the lights are actually on, but at low level and probably not illuminating the sign,

4) is actually a cool idea. I expect the security scenario may want RGB pictures taken in low light environments, so an on-demand light source would be useful.

**Comment by nilsbore** [comment] 2013-10-14 09:20
@gestom 2) Yes, I received that image from either of the two topics on IR. However, I did it on my computer as the robot was patrolling. Also, the room was lit at that moment.

**Comment by nilsbore** [comment] 2013-10-14 09:52
I've checked it out again, and the quality of the image is really bad when you get as little as two meters away.
![far](https://f.cloud.github.com/assets/4670159/1324630/56fd9712-34b6-11e3-8b2c-0deac9849705.png)

**Comment by gestom** [comment] 2013-10-14 19:18
Buy something like this:
http://www.diy.com/nav/decor/lighting/light-bulbs/led_bulbs/Diall-LED-4-5W-MR16-GU5-3-12418964?skuId=12939670 + holder

Hook the wires to the power lines at the PTU platform and use the American screwdriver to fix it in place :
![ptu2](https://f.cloud.github.com/assets/4293593/1328577/98540a0e-3504-11e3-8646-f2a78c0f500b.jpg)
![ptu3](https://f.cloud.github.com/assets/4293593/1328578/9870a470-3504-11e3-8c65-1309ef996ce9.jpg)

Works reasonably http://www.youtube.com/watch?v=jxmgsPZRf2A, but I will test Linda to run with it over night.
As soon as the previous visual charging pull request is merged, I will open a new one, which implements the on-demand light.

**Comment by hawesie** [comment] 2013-10-14 20:43
Super cool!

**Comment by marc-hanheide** [comment] 2013-10-14 22:29
great! @gestom have you checked that the light isn't interfering with the point cloud? It appears to be suspiciously close to the projector of the ASUS...

**Comment by gestom** [comment] 2013-10-14 22:50
The point cloud seems to be fine for now. However, we'll need to find a better way to fix the spotlight, so it does not block the ASUS accidentally. Moreover, the power line for the lights were supposed to be used for the stereocameras, so this is probably a temporary solution only.

**Comment by arbeitor** [comment] 2013-10-15 04:45
awesome! 
one alternative to dock in the dark would be to use directly the point cloud from the asus (specially once the second camera is mounted on the chest) to detect the docking station pose directly in the point cloud. The detection should work reasonably well between 1 and 4 meters. This could be used to drive the robot close enough in front of the docking station to do the final docking using the laser scanner (as initially planned during RoAr) or turning on the light source for final visual docking.

**Comment by gestom** [comment] 2013-10-18 10:42
Linda has been using the light for three days without any problems: http://www.youtube.com/watch?v=btYD1HJo8yA.

**Closed as completed by gestom** 2013-10-18 10:42 UTC

**Comment by bfalacerda** [comment] 2013-10-18 10:44
cool! Is there a way to control the light in our software?

**Comment by gestom** [comment] 2013-10-18 10:50
Yeap, the visual charging is controlling it via the mira bridge - thanks to @cburbridge who made the EBC dynamically reconfigurable parameters. 
The
rosrun dynamic_reconfigure dynparam set /EBC 'Port0_12V_Enabled' True
rosrun dynamic_reconfigure dynparam set /EBC 'Port0_12V_Enabled' False
should turn on and off the light.

**Comment by johnfolk** [comment] 2013-10-18 11:13
eery but cool!
